/*
 * SimuladorFinancieroView.java
 */

package simuladorfinanciero;

import Modelos.FormulasAnalisisFinanciero;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class SimuladorFinancieroView extends FrameView {

    public SimuladorFinancieroView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = SimuladorFinancieroApp.getApplication().getMainFrame();
            aboutBox = new SimuladorFinancieroAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        SimuladorFinancieroApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Instruciones = new javax.swing.JLabel();
        tituDeLiquidez = new javax.swing.JLabel();
        tituDeActividad = new javax.swing.JLabel();
        tituDeDeuda = new javax.swing.JLabel();
        tituDeRentabilidad = new javax.swing.JLabel();
        capitalDeTrabajoNeto = new javax.swing.JButton();
        tituCalcuLiquidez = new javax.swing.JLabel();
        razonCirculante = new javax.swing.JToggleButton();
        razonRapida = new javax.swing.JButton();
        tituCalcuActividad = new javax.swing.JLabel();
        rotacionDeInventario = new javax.swing.JButton();
        cobroPorDia = new javax.swing.JButton();
        cobroAnual = new javax.swing.JButton();
        pagoPorDia = new javax.swing.JButton();
        pagoAnual = new javax.swing.JButton();
        rotacionDeActivosTotales = new javax.swing.JButton();
        tituCalcuRentabilidad = new javax.swing.JLabel();
        utilidadBrutaVCVV = new javax.swing.JButton();
        utilidadBrutaUNV = new javax.swing.JButton();
        utilidadOperativa = new javax.swing.JButton();
        utilidadNeta = new javax.swing.JButton();
        utilidadSobreActivos = new javax.swing.JButton();
        utilidadSobreCapitalContable = new javax.swing.JButton();
        razonDeDeuda = new javax.swing.JButton();
        capacidadDePagoDeIntereses = new javax.swing.JButton();
        tituCalcuDeuda = new javax.swing.JLabel();
        statusPanel = new javax.swing.JPanel();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        statusPanelSeparator = new javax.swing.JSeparator();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        jProgressBar1 = new javax.swing.JProgressBar();
        razonCircualanteFrame = new javax.swing.JFrame();
        tituloInstr = new javax.swing.JLabel();
        tituActivoCirculante = new javax.swing.JLabel();
        tituPasivoCirculante = new javax.swing.JLabel();
        activoCirculante = new javax.swing.JTextField();
        pasivoCirculante = new javax.swing.JTextField();
        resolverRazonCirculante = new javax.swing.JToggleButton();
        tituResul = new javax.swing.JLabel();
        resultadoRazonCirculante = new javax.swing.JLabel();
        capitalTrabajoFrame = new javax.swing.JFrame();
        tituloInstr1 = new javax.swing.JLabel();
        tituActivoCirculante1 = new javax.swing.JLabel();
        tituPasivoCirculante1 = new javax.swing.JLabel();
        activoCirculante1 = new javax.swing.JTextField();
        pasivoCirculante1 = new javax.swing.JTextField();
        resolver1 = new javax.swing.JToggleButton();
        tituResul1 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        razonRapidaFrame = new javax.swing.JFrame();
        instru = new javax.swing.JLabel();
        tituAct = new javax.swing.JLabel();
        tituInv = new javax.swing.JLabel();
        tituPasCir = new javax.swing.JLabel();
        txtActi = new javax.swing.JTextField();
        txtInv = new javax.swing.JTextField();
        txtPasCir = new javax.swing.JTextField();
        resolverRazonRapida = new javax.swing.JButton();
        tituRes = new javax.swing.JLabel();
        resRazonRapida = new javax.swing.JLabel();
        rotacionDeInventarioFrame = new javax.swing.JFrame();
        instrudeInventario = new javax.swing.JLabel();
        tituCostoVentas = new javax.swing.JLabel();
        tituInven = new javax.swing.JLabel();
        txtCosVen = new javax.swing.JTextField();
        txtInvn = new javax.swing.JTextField();
        resolverRotacionInventario = new javax.swing.JButton();
        tituresu = new javax.swing.JLabel();
        resultadoRotacionInventario = new javax.swing.JLabel();
        promedioDeCobroDiaFrame = new javax.swing.JFrame();
        instrudeInventario1 = new javax.swing.JLabel();
        tituCuentas = new javax.swing.JLabel();
        tituVentasxDia = new javax.swing.JLabel();
        txtCuentasxCobrar = new javax.swing.JTextField();
        txtVentxDia = new javax.swing.JTextField();
        resPromedioCobroDia = new javax.swing.JButton();
        tituresu1 = new javax.swing.JLabel();
        resultadoPromedioCobroDia = new javax.swing.JLabel();
        promedioDeCobroAnualFrame = new javax.swing.JFrame();
        instrudeInventario2 = new javax.swing.JLabel();
        tituCuentas1 = new javax.swing.JLabel();
        tituVentasxDia1 = new javax.swing.JLabel();
        txtCuentasxCobrar1 = new javax.swing.JTextField();
        txtVentxAnual = new javax.swing.JTextField();
        resPromedioCobroAnual = new javax.swing.JButton();
        tituresu2 = new javax.swing.JLabel();
        resultadoPromedioCobroAnual = new javax.swing.JLabel();
        promedioDePagoPorDiaFrame = new javax.swing.JFrame();
        instrudeInventario3 = new javax.swing.JLabel();
        tituCuentas2 = new javax.swing.JLabel();
        tituVentasxDia2 = new javax.swing.JLabel();
        txtCuentasxCobrar2 = new javax.swing.JTextField();
        txtVentxAnual1 = new javax.swing.JTextField();
        resPromedioPagoPorDia = new javax.swing.JButton();
        tituresu3 = new javax.swing.JLabel();
        resultadoPromedioCobroAnual1 = new javax.swing.JLabel();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(simuladorfinanciero.SimuladorFinancieroApp.class).getContext().getResourceMap(SimuladorFinancieroView.class);
        Titulo.setText(resourceMap.getString("Titulo.text")); // NOI18N
        Titulo.setName("Titulo"); // NOI18N

        Instruciones.setText(resourceMap.getString("Instruciones.text")); // NOI18N
        Instruciones.setName("Instruciones"); // NOI18N

        tituDeLiquidez.setText(resourceMap.getString("tituDeLiquidez.text")); // NOI18N
        tituDeLiquidez.setName("tituDeLiquidez"); // NOI18N

        tituDeActividad.setText(resourceMap.getString("tituDeActividad.text")); // NOI18N
        tituDeActividad.setName("tituDeActividad"); // NOI18N

        tituDeDeuda.setText(resourceMap.getString("tituDeDeuda.text")); // NOI18N
        tituDeDeuda.setName("tituDeDeuda"); // NOI18N

        tituDeRentabilidad.setText(resourceMap.getString("tituDeRentabilidad.text")); // NOI18N
        tituDeRentabilidad.setName("tituDeRentabilidad"); // NOI18N

        capitalDeTrabajoNeto.setText(resourceMap.getString("capitalDeTrabajoNeto.text")); // NOI18N
        capitalDeTrabajoNeto.setName("capitalDeTrabajoNeto"); // NOI18N
        capitalDeTrabajoNeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                capitalDeTrabajoNetoMouseClicked(evt);
            }
        });

        tituCalcuLiquidez.setFont(resourceMap.getFont("tituCalcuLiquidez.font")); // NOI18N
        tituCalcuLiquidez.setText(resourceMap.getString("tituCalcuLiquidez.text")); // NOI18N
        tituCalcuLiquidez.setName("tituCalcuLiquidez"); // NOI18N

        razonCirculante.setText(resourceMap.getString("razonCirculante.text")); // NOI18N
        razonCirculante.setName("razonCirculante"); // NOI18N
        razonCirculante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                razonCirculanteMouseClicked(evt);
            }
        });

        razonRapida.setText(resourceMap.getString("razonRapida.text")); // NOI18N
        razonRapida.setName("razonRapida"); // NOI18N
        razonRapida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                razonRapidaMouseClicked(evt);
            }
        });

        tituCalcuActividad.setFont(resourceMap.getFont("tituCalcuActividad.font")); // NOI18N
        tituCalcuActividad.setText(resourceMap.getString("tituCalcuActividad.text")); // NOI18N
        tituCalcuActividad.setName("tituCalcuActividad"); // NOI18N

        rotacionDeInventario.setText(resourceMap.getString("rotacionDeInventario.text")); // NOI18N
        rotacionDeInventario.setName("rotacionDeInventario"); // NOI18N
        rotacionDeInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rotacionDeInventarioMouseClicked(evt);
            }
        });

        cobroPorDia.setText(resourceMap.getString("cobroPorDia.text")); // NOI18N
        cobroPorDia.setName("cobroPorDia"); // NOI18N
        cobroPorDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cobroPorDiaMouseClicked(evt);
            }
        });

        cobroAnual.setText(resourceMap.getString("cobroAnual.text")); // NOI18N
        cobroAnual.setName("cobroAnual"); // NOI18N
        cobroAnual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cobroAnualMouseClicked(evt);
            }
        });

        pagoPorDia.setText(resourceMap.getString("pagoPorDia.text")); // NOI18N
        pagoPorDia.setName("pagoPorDia"); // NOI18N
        pagoPorDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagoPorDiaMouseClicked(evt);
            }
        });

        pagoAnual.setText(resourceMap.getString("pagoAnual.text")); // NOI18N
        pagoAnual.setName("pagoAnual"); // NOI18N
        pagoAnual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagoAnualMouseClicked(evt);
            }
        });

        rotacionDeActivosTotales.setText(resourceMap.getString("rotacionDeActivosTotales.text")); // NOI18N
        rotacionDeActivosTotales.setName("rotacionDeActivosTotales"); // NOI18N
        rotacionDeActivosTotales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rotacionDeActivosTotalesMouseClicked(evt);
            }
        });

        tituCalcuRentabilidad.setFont(resourceMap.getFont("tituCalcuRentabilidad.font")); // NOI18N
        tituCalcuRentabilidad.setText(resourceMap.getString("tituCalcuRentabilidad.text")); // NOI18N
        tituCalcuRentabilidad.setName("tituCalcuRentabilidad"); // NOI18N

        utilidadBrutaVCVV.setText(resourceMap.getString("utilidadBrutaVCVV.text")); // NOI18N
        utilidadBrutaVCVV.setName("utilidadBrutaVCVV"); // NOI18N
        utilidadBrutaVCVV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilidadBrutaVCVVMouseClicked(evt);
            }
        });

        utilidadBrutaUNV.setText(resourceMap.getString("utilidadBrutaUNV.text")); // NOI18N
        utilidadBrutaUNV.setName("utilidadBrutaUNV"); // NOI18N
        utilidadBrutaUNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilidadBrutaUNVMouseClicked(evt);
            }
        });

        utilidadOperativa.setText(resourceMap.getString("utilidadOperativa.text")); // NOI18N
        utilidadOperativa.setName("utilidadOperativa"); // NOI18N
        utilidadOperativa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilidadOperativaMouseClicked(evt);
            }
        });

        utilidadNeta.setText(resourceMap.getString("utilidadNeta.text")); // NOI18N
        utilidadNeta.setName("utilidadNeta"); // NOI18N
        utilidadNeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilidadNetaMouseClicked(evt);
            }
        });

        utilidadSobreActivos.setText(resourceMap.getString("utilidadSobreActivos.text")); // NOI18N
        utilidadSobreActivos.setName("utilidadSobreActivos"); // NOI18N
        utilidadSobreActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilidadSobreActivosMouseClicked(evt);
            }
        });

        utilidadSobreCapitalContable.setText(resourceMap.getString("utilidadSobreCapitalContable.text")); // NOI18N
        utilidadSobreCapitalContable.setName("utilidadSobreCapitalContable"); // NOI18N
        utilidadSobreCapitalContable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utilidadSobreCapitalContableMouseClicked(evt);
            }
        });

        razonDeDeuda.setText(resourceMap.getString("razonDeDeuda.text")); // NOI18N
        razonDeDeuda.setName("razonDeDeuda"); // NOI18N
        razonDeDeuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                razonDeDeudaMouseClicked(evt);
            }
        });

        capacidadDePagoDeIntereses.setText(resourceMap.getString("capacidadDePagoDeIntereses.text")); // NOI18N
        capacidadDePagoDeIntereses.setName("capacidadDePagoDeIntereses"); // NOI18N
        capacidadDePagoDeIntereses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                capacidadDePagoDeInteresesMouseClicked(evt);
            }
        });

        tituCalcuDeuda.setFont(resourceMap.getFont("tituCalcuDeuda.font")); // NOI18N
        tituCalcuDeuda.setText(resourceMap.getString("tituCalcuDeuda.text")); // NOI18N
        tituCalcuDeuda.setName("tituCalcuDeuda"); // NOI18N

        statusPanel.setName("statusPanel"); // NOI18N

        statusMessageLabel.setText(resourceMap.getString("statusMessageLabel.text")); // NOI18N
        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setText(resourceMap.getString("statusAnimationLabel.text")); // NOI18N
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        org.jdesktop.layout.GroupLayout statusPanelLayout = new org.jdesktop.layout.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(statusMessageLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 533, Short.MAX_VALUE)
                .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(36, 36, 36)
                .add(statusAnimationLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(181, 181, 181))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, statusAnimationLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .add(statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(statusMessageLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(mainPanelLayout.createSequentialGroup()
                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(mainPanelLayout.createSequentialGroup()
                                        .add(78, 78, 78)
                                        .add(tituDeLiquidez))
                                    .add(mainPanelLayout.createSequentialGroup()
                                        .add(20, 20, 20)
                                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(mainPanelLayout.createSequentialGroup()
                                                .add(21, 21, 21)
                                                .add(razonCirculante))
                                            .add(capitalDeTrabajoNeto))))
                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(mainPanelLayout.createSequentialGroup()
                                        .add(86, 86, 86)
                                        .add(tituDeActividad)
                                        .add(150, 150, 150)
                                        .add(tituDeRentabilidad))
                                    .add(mainPanelLayout.createSequentialGroup()
                                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(mainPanelLayout.createSequentialGroup()
                                                .add(10, 10, 10)
                                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(cobroPorDia)
                                                    .add(pagoAnual)
                                                    .add(cobroAnual)
                                                    .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                        .add(rotacionDeActivosTotales)
                                                        .add(pagoPorDia))))
                                            .add(mainPanelLayout.createSequentialGroup()
                                                .add(32, 32, 32)
                                                .add(rotacionDeInventario)))
                                        .add(47, 47, 47)
                                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                                            .add(tituCalcuRentabilidad)
                                            .add(utilidadBrutaVCVV)
                                            .add(utilidadSobreActivos)
                                            .add(utilidadSobreCapitalContable)
                                            .add(utilidadNeta)
                                            .add(utilidadOperativa)
                                            .add(utilidadBrutaUNV)))))
                            .add(mainPanelLayout.createSequentialGroup()
                                .add(50, 50, 50)
                                .add(razonRapida)))
                        .add(68, 68, 68)
                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                            .add(tituDeDeuda)
                            .add(razonDeDeuda)
                            .add(capacidadDePagoDeIntereses)
                            .add(tituCalcuDeuda)))
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(111, 111, 111)
                        .add(tituCalcuLiquidez)
                        .add(177, 177, 177)
                        .add(tituCalcuActividad))
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(42, 42, 42)
                        .add(statusPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(statusPanelSeparator)
                    .add(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(Titulo))
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(Instruciones)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .add(60, 60, 60)
                .add(Titulo)
                .add(39, 39, 39)
                .add(Instruciones)
                .add(39, 39, 39)
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(tituDeDeuda)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(tituCalcuDeuda)
                        .add(11, 11, 11)
                        .add(razonDeDeuda)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(capacidadDePagoDeIntereses))
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(tituDeLiquidez)
                            .add(tituDeActividad)
                            .add(tituDeRentabilidad))
                        .add(18, 18, 18)
                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(mainPanelLayout.createSequentialGroup()
                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(tituCalcuLiquidez)
                                    .add(tituCalcuActividad))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(capitalDeTrabajoNeto)
                                    .add(rotacionDeInventario))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(razonCirculante)
                                    .add(cobroPorDia))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(razonRapida)
                                    .add(cobroAnual))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pagoPorDia)
                                .add(4, 4, 4)
                                .add(pagoAnual)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rotacionDeActivosTotales))
                            .add(mainPanelLayout.createSequentialGroup()
                                .add(tituCalcuRentabilidad)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(utilidadBrutaVCVV)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(utilidadBrutaUNV)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(utilidadOperativa)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(utilidadNeta)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(utilidadSobreActivos)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(utilidadSobreCapitalContable)))))
                .add(18, 18, 18)
                .add(statusPanelSeparator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(simuladorfinanciero.SimuladorFinancieroApp.class).getContext().getActionMap(SimuladorFinancieroView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        exitMenuItem1.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem1.setName("exitMenuItem1"); // NOI18N
        fileMenu.add(exitMenuItem1);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        jProgressBar1.setName("jProgressBar1"); // NOI18N

        razonCircualanteFrame.setTitle(resourceMap.getString("razonCircualanteFrame.title")); // NOI18N
        razonCircualanteFrame.setName("razonCircualanteFrame"); // NOI18N

        tituloInstr.setText(resourceMap.getString("tituloInstr.text")); // NOI18N
        tituloInstr.setName("tituloInstr"); // NOI18N

        tituActivoCirculante.setText(resourceMap.getString("tituActivoCirculante.text")); // NOI18N
        tituActivoCirculante.setName("tituActivoCirculante"); // NOI18N

        tituPasivoCirculante.setText(resourceMap.getString("tituPasivoCirculante.text")); // NOI18N
        tituPasivoCirculante.setName("tituPasivoCirculante"); // NOI18N

        activoCirculante.setText(resourceMap.getString("activoCirculante.text")); // NOI18N
        activoCirculante.setName("activoCirculante"); // NOI18N

        pasivoCirculante.setText(resourceMap.getString("pasivoCirculante.text")); // NOI18N
        pasivoCirculante.setName("pasivoCirculante"); // NOI18N

        resolverRazonCirculante.setName("resolverRazonCirculante"); // NOI18N
        resolverRazonCirculante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resolverRazonCirculanteMouseClicked(evt);
            }
        });

        tituResul.setText(resourceMap.getString("tituResul.text")); // NOI18N
        tituResul.setName("tituResul"); // NOI18N

        resultadoRazonCirculante.setText(resourceMap.getString("resultadoRazonCirculante.text")); // NOI18N
        resultadoRazonCirculante.setName("resultadoRazonCirculante"); // NOI18N

        org.jdesktop.layout.GroupLayout razonCircualanteFrameLayout = new org.jdesktop.layout.GroupLayout(razonCircualanteFrame.getContentPane());
        razonCircualanteFrame.getContentPane().setLayout(razonCircualanteFrameLayout);
        razonCircualanteFrameLayout.setHorizontalGroup(
            razonCircualanteFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(razonCircualanteFrameLayout.createSequentialGroup()
                .add(razonCircualanteFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(razonCircualanteFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(tituloInstr))
                    .add(razonCircualanteFrameLayout.createSequentialGroup()
                        .add(57, 57, 57)
                        .add(razonCircualanteFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(tituPasivoCirculante)
                            .add(tituActivoCirculante)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, resolverRazonCirculante))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(razonCircualanteFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(razonCircualanteFrameLayout.createSequentialGroup()
                                .add(tituResul)
                                .add(18, 18, 18)
                                .add(resultadoRazonCirculante))
                            .add(razonCircualanteFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(pasivoCirculante)
                                .add(activoCirculante, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        razonCircualanteFrameLayout.setVerticalGroup(
            razonCircualanteFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(razonCircualanteFrameLayout.createSequentialGroup()
                .add(28, 28, 28)
                .add(tituloInstr)
                .add(42, 42, 42)
                .add(razonCircualanteFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituActivoCirculante)
                    .add(activoCirculante, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(razonCircualanteFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituPasivoCirculante)
                    .add(pasivoCirculante, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(33, 33, 33)
                .add(razonCircualanteFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(resolverRazonCirculante)
                    .add(tituResul)
                    .add(resultadoRazonCirculante))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        capitalTrabajoFrame.setTitle(resourceMap.getString("capitalTrabajoFrame.title")); // NOI18N
        capitalTrabajoFrame.setName("capitalTrabajoFrame"); // NOI18N

        tituloInstr1.setText(resourceMap.getString("tituloInstr1.text")); // NOI18N
        tituloInstr1.setName("tituloInstr1"); // NOI18N

        tituActivoCirculante1.setText(resourceMap.getString("tituActivoCirculante1.text")); // NOI18N
        tituActivoCirculante1.setName("tituActivoCirculante1"); // NOI18N

        tituPasivoCirculante1.setText(resourceMap.getString("tituPasivoCirculante1.text")); // NOI18N
        tituPasivoCirculante1.setName("tituPasivoCirculante1"); // NOI18N

        activoCirculante1.setName("activoCirculante1"); // NOI18N

        pasivoCirculante1.setName("pasivoCirculante1"); // NOI18N

        resolver1.setText(resourceMap.getString("resolver1.text")); // NOI18N
        resolver1.setName("resolver1"); // NOI18N
        resolver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resolver1MouseClicked(evt);
            }
        });

        tituResul1.setText(resourceMap.getString("tituResul1.text")); // NOI18N
        tituResul1.setName("tituResul1"); // NOI18N

        resultado.setText(resourceMap.getString("resultado.text")); // NOI18N
        resultado.setName("resultado"); // NOI18N

        org.jdesktop.layout.GroupLayout capitalTrabajoFrameLayout = new org.jdesktop.layout.GroupLayout(capitalTrabajoFrame.getContentPane());
        capitalTrabajoFrame.getContentPane().setLayout(capitalTrabajoFrameLayout);
        capitalTrabajoFrameLayout.setHorizontalGroup(
            capitalTrabajoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 404, Short.MAX_VALUE)
            .add(capitalTrabajoFrameLayout.createSequentialGroup()
                .add(capitalTrabajoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(capitalTrabajoFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(tituloInstr1))
                    .add(capitalTrabajoFrameLayout.createSequentialGroup()
                        .add(57, 57, 57)
                        .add(capitalTrabajoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(tituPasivoCirculante1)
                            .add(tituActivoCirculante1)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, resolver1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(capitalTrabajoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(capitalTrabajoFrameLayout.createSequentialGroup()
                                .add(tituResul1)
                                .add(32, 32, 32)
                                .add(resultado))
                            .add(capitalTrabajoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(pasivoCirculante1)
                                .add(activoCirculante1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        capitalTrabajoFrameLayout.setVerticalGroup(
            capitalTrabajoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 267, Short.MAX_VALUE)
            .add(capitalTrabajoFrameLayout.createSequentialGroup()
                .add(28, 28, 28)
                .add(tituloInstr1)
                .add(42, 42, 42)
                .add(capitalTrabajoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituActivoCirculante1)
                    .add(activoCirculante1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(capitalTrabajoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituPasivoCirculante1)
                    .add(pasivoCirculante1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(33, 33, 33)
                .add(capitalTrabajoFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(resolver1)
                    .add(tituResul1)
                    .add(resultado))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        razonRapidaFrame.setTitle(resourceMap.getString("razonRapidaFrame.title")); // NOI18N
        razonRapidaFrame.setName("razonRapidaFrame"); // NOI18N

        instru.setText(resourceMap.getString("instru.text")); // NOI18N
        instru.setName("instru"); // NOI18N

        tituAct.setText(resourceMap.getString("tituAct.text")); // NOI18N
        tituAct.setName("tituAct"); // NOI18N

        tituInv.setText(resourceMap.getString("tituInv.text")); // NOI18N
        tituInv.setName("tituInv"); // NOI18N

        tituPasCir.setText(resourceMap.getString("tituPasCir.text")); // NOI18N
        tituPasCir.setName("tituPasCir"); // NOI18N

        txtActi.setText(resourceMap.getString("txtActi.text")); // NOI18N
        txtActi.setName("txtActi"); // NOI18N

        txtInv.setText(resourceMap.getString("txtInv.text")); // NOI18N
        txtInv.setName("txtInv"); // NOI18N

        txtPasCir.setText(resourceMap.getString("txtPasCir.text")); // NOI18N
        txtPasCir.setName("txtPasCir"); // NOI18N

        resolverRazonRapida.setText(resourceMap.getString("resolverRazonRapida.text")); // NOI18N
        resolverRazonRapida.setName("resolverRazonRapida"); // NOI18N
        resolverRazonRapida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resolverRazonRapidaMouseClicked(evt);
            }
        });

        tituRes.setText(resourceMap.getString("tituRes.text")); // NOI18N
        tituRes.setName("tituRes"); // NOI18N

        resRazonRapida.setText(resourceMap.getString("resRazonRapida.text")); // NOI18N
        resRazonRapida.setName("resRazonRapida"); // NOI18N

        org.jdesktop.layout.GroupLayout razonRapidaFrameLayout = new org.jdesktop.layout.GroupLayout(razonRapidaFrame.getContentPane());
        razonRapidaFrame.getContentPane().setLayout(razonRapidaFrameLayout);
        razonRapidaFrameLayout.setHorizontalGroup(
            razonRapidaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(razonRapidaFrameLayout.createSequentialGroup()
                .add(razonRapidaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(razonRapidaFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(instru))
                    .add(razonRapidaFrameLayout.createSequentialGroup()
                        .add(94, 94, 94)
                        .add(razonRapidaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(tituInv)
                            .add(tituAct)
                            .add(tituPasCir))
                        .add(29, 29, 29)
                        .add(razonRapidaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(txtActi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .add(txtInv)
                            .add(txtPasCir)))
                    .add(razonRapidaFrameLayout.createSequentialGroup()
                        .add(62, 62, 62)
                        .add(resolverRazonRapida)
                        .add(64, 64, 64)
                        .add(tituRes)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(resRazonRapida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        razonRapidaFrameLayout.setVerticalGroup(
            razonRapidaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(razonRapidaFrameLayout.createSequentialGroup()
                .add(54, 54, 54)
                .add(instru)
                .add(29, 29, 29)
                .add(razonRapidaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituAct)
                    .add(txtActi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(razonRapidaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituInv)
                    .add(txtInv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(razonRapidaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituPasCir)
                    .add(txtPasCir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(razonRapidaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(razonRapidaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(resolverRazonRapida)
                        .add(tituRes))
                    .add(resRazonRapida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(32, 32, 32))
        );

        rotacionDeInventarioFrame.setTitle(resourceMap.getString("rotacionDeInventarioFrame.title")); // NOI18N
        rotacionDeInventarioFrame.setName("rotacionDeInventarioFrame"); // NOI18N

        instrudeInventario.setText(resourceMap.getString("instrudeInventario.text")); // NOI18N
        instrudeInventario.setName("instrudeInventario"); // NOI18N

        tituCostoVentas.setText(resourceMap.getString("tituCostoVentas.text")); // NOI18N
        tituCostoVentas.setName("tituCostoVentas"); // NOI18N

        tituInven.setText(resourceMap.getString("tituInven.text")); // NOI18N
        tituInven.setName("tituInven"); // NOI18N

        txtCosVen.setText(resourceMap.getString("txtCosVen.text")); // NOI18N
        txtCosVen.setName("txtCosVen"); // NOI18N

        txtInvn.setText(resourceMap.getString("txtInvn.text")); // NOI18N
        txtInvn.setName("txtInvn"); // NOI18N

        resolverRotacionInventario.setText(resourceMap.getString("resolverRotacionInventario.text")); // NOI18N
        resolverRotacionInventario.setName("resolverRotacionInventario"); // NOI18N
        resolverRotacionInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resolverRotacionInventarioMouseClicked(evt);
            }
        });

        tituresu.setText(resourceMap.getString("tituresu.text")); // NOI18N
        tituresu.setName("tituresu"); // NOI18N

        resultadoRotacionInventario.setText(resourceMap.getString("resultadoRotacionInventario.text")); // NOI18N
        resultadoRotacionInventario.setName("resultadoRotacionInventario"); // NOI18N

        org.jdesktop.layout.GroupLayout rotacionDeInventarioFrameLayout = new org.jdesktop.layout.GroupLayout(rotacionDeInventarioFrame.getContentPane());
        rotacionDeInventarioFrame.getContentPane().setLayout(rotacionDeInventarioFrameLayout);
        rotacionDeInventarioFrameLayout.setHorizontalGroup(
            rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rotacionDeInventarioFrameLayout.createSequentialGroup()
                .add(rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rotacionDeInventarioFrameLayout.createSequentialGroup()
                        .add(72, 72, 72)
                        .add(rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(tituCostoVentas)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, resolverRotacionInventario))
                            .add(tituInven))
                        .add(rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(rotacionDeInventarioFrameLayout.createSequentialGroup()
                                .add(58, 58, 58)
                                .add(tituresu)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(resultadoRotacionInventario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(rotacionDeInventarioFrameLayout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtInvn)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtCosVen, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))))
                    .add(rotacionDeInventarioFrameLayout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(instrudeInventario)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        rotacionDeInventarioFrameLayout.setVerticalGroup(
            rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(rotacionDeInventarioFrameLayout.createSequentialGroup()
                .add(55, 55, 55)
                .add(instrudeInventario)
                .add(35, 35, 35)
                .add(rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituCostoVentas)
                    .add(txtCosVen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituInven)
                    .add(txtInvn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 39, Short.MAX_VALUE)
                .add(rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(rotacionDeInventarioFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(resolverRotacionInventario)
                        .add(tituresu))
                    .add(resultadoRotacionInventario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(41, 41, 41))
        );

        promedioDeCobroDiaFrame.setTitle(resourceMap.getString("promedioDeCobroDiaFrame.title")); // NOI18N
        promedioDeCobroDiaFrame.setName("promedioDeCobroDiaFrame"); // NOI18N

        instrudeInventario1.setText(resourceMap.getString("instrudeInventario1.text")); // NOI18N
        instrudeInventario1.setName("instrudeInventario1"); // NOI18N

        tituCuentas.setText(resourceMap.getString("tituCuentas.text")); // NOI18N
        tituCuentas.setName("tituCuentas"); // NOI18N

        tituVentasxDia.setText(resourceMap.getString("tituVentasxDia.text")); // NOI18N
        tituVentasxDia.setName("tituVentasxDia"); // NOI18N

        txtCuentasxCobrar.setName("txtCuentasxCobrar"); // NOI18N

        txtVentxDia.setName("txtVentxDia"); // NOI18N

        resPromedioCobroDia.setText(resourceMap.getString("resPromedioCobroDia.text")); // NOI18N
        resPromedioCobroDia.setName("resPromedioCobroDia"); // NOI18N
        resPromedioCobroDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resPromedioCobroDiaMouseClicked(evt);
            }
        });

        tituresu1.setText(resourceMap.getString("tituresu1.text")); // NOI18N
        tituresu1.setName("tituresu1"); // NOI18N

        resultadoPromedioCobroDia.setName("resultadoPromedioCobroDia"); // NOI18N

        org.jdesktop.layout.GroupLayout promedioDeCobroDiaFrameLayout = new org.jdesktop.layout.GroupLayout(promedioDeCobroDiaFrame.getContentPane());
        promedioDeCobroDiaFrame.getContentPane().setLayout(promedioDeCobroDiaFrameLayout);
        promedioDeCobroDiaFrameLayout.setHorizontalGroup(
            promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(promedioDeCobroDiaFrameLayout.createSequentialGroup()
                .add(promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(promedioDeCobroDiaFrameLayout.createSequentialGroup()
                        .add(72, 72, 72)
                        .add(promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(tituCuentas)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, resPromedioCobroDia))
                            .add(tituVentasxDia))
                        .add(promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(promedioDeCobroDiaFrameLayout.createSequentialGroup()
                                .add(58, 58, 58)
                                .add(tituresu1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(resultadoPromedioCobroDia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(promedioDeCobroDiaFrameLayout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtVentxDia)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtCuentasxCobrar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))))
                    .add(promedioDeCobroDiaFrameLayout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(instrudeInventario1)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        promedioDeCobroDiaFrameLayout.setVerticalGroup(
            promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(promedioDeCobroDiaFrameLayout.createSequentialGroup()
                .add(55, 55, 55)
                .add(instrudeInventario1)
                .add(35, 35, 35)
                .add(promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituCuentas)
                    .add(txtCuentasxCobrar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituVentasxDia)
                    .add(txtVentxDia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 39, Short.MAX_VALUE)
                .add(promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(promedioDeCobroDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(resPromedioCobroDia)
                        .add(tituresu1))
                    .add(resultadoPromedioCobroDia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(41, 41, 41))
        );

        promedioDeCobroAnualFrame.setTitle(resourceMap.getString("promedioDeCobroAnualFrame.title")); // NOI18N
        promedioDeCobroAnualFrame.setName("promedioDeCobroAnualFrame"); // NOI18N

        instrudeInventario2.setText(resourceMap.getString("instrudeInventario2.text")); // NOI18N
        instrudeInventario2.setName("instrudeInventario2"); // NOI18N

        tituCuentas1.setText(resourceMap.getString("tituCuentas1.text")); // NOI18N
        tituCuentas1.setName("tituCuentas1"); // NOI18N

        tituVentasxDia1.setText(resourceMap.getString("tituVentasxDia1.text")); // NOI18N
        tituVentasxDia1.setName("tituVentasxDia1"); // NOI18N

        txtCuentasxCobrar1.setName("txtCuentasxCobrar1"); // NOI18N

        txtVentxAnual.setName("txtVentxAnual"); // NOI18N

        resPromedioCobroAnual.setText(resourceMap.getString("resPromedioCobroAnual.text")); // NOI18N
        resPromedioCobroAnual.setName("resPromedioCobroAnual"); // NOI18N
        resPromedioCobroAnual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resPromedioCobroAnualMouseClicked(evt);
            }
        });

        tituresu2.setText(resourceMap.getString("tituresu2.text")); // NOI18N
        tituresu2.setName("tituresu2"); // NOI18N

        resultadoPromedioCobroAnual.setName("resultadoPromedioCobroAnual"); // NOI18N

        org.jdesktop.layout.GroupLayout promedioDeCobroAnualFrameLayout = new org.jdesktop.layout.GroupLayout(promedioDeCobroAnualFrame.getContentPane());
        promedioDeCobroAnualFrame.getContentPane().setLayout(promedioDeCobroAnualFrameLayout);
        promedioDeCobroAnualFrameLayout.setHorizontalGroup(
            promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(promedioDeCobroAnualFrameLayout.createSequentialGroup()
                .add(promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(promedioDeCobroAnualFrameLayout.createSequentialGroup()
                        .add(72, 72, 72)
                        .add(promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(tituCuentas1)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, resPromedioCobroAnual))
                            .add(tituVentasxDia1))
                        .add(promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(promedioDeCobroAnualFrameLayout.createSequentialGroup()
                                .add(58, 58, 58)
                                .add(tituresu2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(resultadoPromedioCobroAnual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(promedioDeCobroAnualFrameLayout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtVentxAnual)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtCuentasxCobrar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))))
                    .add(promedioDeCobroAnualFrameLayout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(instrudeInventario2)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        promedioDeCobroAnualFrameLayout.setVerticalGroup(
            promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(promedioDeCobroAnualFrameLayout.createSequentialGroup()
                .add(55, 55, 55)
                .add(instrudeInventario2)
                .add(35, 35, 35)
                .add(promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituCuentas1)
                    .add(txtCuentasxCobrar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituVentasxDia1)
                    .add(txtVentxAnual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 39, Short.MAX_VALUE)
                .add(promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(promedioDeCobroAnualFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(resPromedioCobroAnual)
                        .add(tituresu2))
                    .add(resultadoPromedioCobroAnual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(41, 41, 41))
        );

        promedioDePagoPorDiaFrame.setName("promedioDePagoPorDiaFrame"); // NOI18N

        instrudeInventario3.setText(resourceMap.getString("instrudeInventario3.text")); // NOI18N
        instrudeInventario3.setName("instrudeInventario3"); // NOI18N

        tituCuentas2.setText(resourceMap.getString("tituCuentas2.text")); // NOI18N
        tituCuentas2.setName("tituCuentas2"); // NOI18N

        tituVentasxDia2.setText(resourceMap.getString("tituVentasxDia2.text")); // NOI18N
        tituVentasxDia2.setName("tituVentasxDia2"); // NOI18N

        txtCuentasxCobrar2.setName("txtCuentasxCobrar2"); // NOI18N

        txtVentxAnual1.setName("txtVentxAnual1"); // NOI18N

        resPromedioPagoPorDia.setText(resourceMap.getString("resPromedioPagoPorDia.text")); // NOI18N
        resPromedioPagoPorDia.setName("resPromedioPagoPorDia"); // NOI18N

        tituresu3.setText(resourceMap.getString("tituresu3.text")); // NOI18N
        tituresu3.setName("tituresu3"); // NOI18N

        resultadoPromedioCobroAnual1.setName("resultadoPromedioCobroAnual1"); // NOI18N

        org.jdesktop.layout.GroupLayout promedioDePagoPorDiaFrameLayout = new org.jdesktop.layout.GroupLayout(promedioDePagoPorDiaFrame.getContentPane());
        promedioDePagoPorDiaFrame.getContentPane().setLayout(promedioDePagoPorDiaFrameLayout);
        promedioDePagoPorDiaFrameLayout.setHorizontalGroup(
            promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 420, Short.MAX_VALUE)
            .add(promedioDePagoPorDiaFrameLayout.createSequentialGroup()
                .add(promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(promedioDePagoPorDiaFrameLayout.createSequentialGroup()
                        .add(72, 72, 72)
                        .add(promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(tituCuentas2)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, resPromedioPagoPorDia))
                            .add(tituVentasxDia2))
                        .add(promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(promedioDePagoPorDiaFrameLayout.createSequentialGroup()
                                .add(58, 58, 58)
                                .add(tituresu3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(resultadoPromedioCobroAnual1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(promedioDePagoPorDiaFrameLayout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtVentxAnual1)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, txtCuentasxCobrar2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))))
                    .add(promedioDePagoPorDiaFrameLayout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(instrudeInventario3)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        promedioDePagoPorDiaFrameLayout.setVerticalGroup(
            promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
            .add(promedioDePagoPorDiaFrameLayout.createSequentialGroup()
                .add(55, 55, 55)
                .add(instrudeInventario3)
                .add(35, 35, 35)
                .add(promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituCuentas2)
                    .add(txtCuentasxCobrar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tituVentasxDia2)
                    .add(txtVentxAnual1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 58, Short.MAX_VALUE)
                .add(promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(promedioDePagoPorDiaFrameLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(resPromedioPagoPorDia)
                        .add(tituresu3))
                    .add(resultadoPromedioCobroAnual1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(41, 41, 41))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void capitalDeTrabajoNetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capitalDeTrabajoNetoMouseClicked
        // TODO add your handling code here:
            capitalTrabajoFrame.setBounds(0, 0, 500, 300);
            capitalTrabajoFrame.setLocationRelativeTo(null); // Centra la ventana.
            capitalTrabajoFrame.setVisible(true);

    }//GEN-LAST:event_capitalDeTrabajoNetoMouseClicked

    private void razonCirculanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_razonCirculanteMouseClicked
        // TODO add your handling code here:
            razonCircualanteFrame.setBounds(0, 0, 500, 300);
            razonCircualanteFrame.setLocationRelativeTo(null); // Centra la ventana.
            razonCircualanteFrame.setVisible(true);
    }//GEN-LAST:event_razonCirculanteMouseClicked

    private void resolver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resolver1MouseClicked
        // TODO add your handling code here:
        FormulasAnalisisFinanciero faf =  new FormulasAnalisisFinanciero();
        Double act, pas;
        String actCirculante = activoCirculante1.getText();
        String pasvoCirculante = pasivoCirculante1.getText();
        act = Double.parseDouble(actCirculante);
        pas = Double.parseDouble(pasvoCirculante);
        Double resul = faf.calcularCapitalTrabajoNeto(act, pas);
        String res = String.valueOf(resul);
        resultado.setText(res);

    }//GEN-LAST:event_resolver1MouseClicked

    private void resolverRazonCirculanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resolverRazonCirculanteMouseClicked
        // TODO add your handling code here:
        FormulasAnalisisFinanciero faf =  new FormulasAnalisisFinanciero();
        Double act, pas;
        String actCirculante = activoCirculante.getText();
        String pasCirculante = pasivoCirculante.getText();
        act = Double.parseDouble(actCirculante);
        pas = Double.parseDouble(pasCirculante);
        Double resul = faf.calcularRazonCirculante(act, pas);
        String res = String.valueOf(resul);
        resultadoRazonCirculante.setText(res);
    }//GEN-LAST:event_resolverRazonCirculanteMouseClicked

    private void razonRapidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_razonRapidaMouseClicked
        // TODO add your handling code here:
            razonRapidaFrame.setBounds(0, 0, 500, 300);
            razonRapidaFrame.setLocationRelativeTo(null); // Centra la ventana.
            razonRapidaFrame.setVisible(true);
    }//GEN-LAST:event_razonRapidaMouseClicked

    private void resolverRazonRapidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resolverRazonRapidaMouseClicked
        // TODO add your handling code here:
        FormulasAnalisisFinanciero faf =  new FormulasAnalisisFinanciero();
        Double actcir, inv, pascir;
        String actcirr = txtActi.getText();
        String invv = txtInv.getText();
        String pascirr = txtPasCir.getText();
        actcir = Double.parseDouble(actcirr);
        inv = Double.parseDouble(invv);
        pascir = Double.parseDouble(pascirr);
        Double resul = faf.calcularRazonRapidaOrPruebaDelAcido(actcir, inv, pascir);
        String res = String.valueOf(resul);
        resRazonRapida.setText(res);
    }//GEN-LAST:event_resolverRazonRapidaMouseClicked

    private void rotacionDeInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotacionDeInventarioMouseClicked
        // TODO add your handling code here:
            rotacionDeInventarioFrame.setBounds(0, 0, 500, 300);
            rotacionDeInventarioFrame.setLocationRelativeTo(null); // Centra la ventana.
            rotacionDeInventarioFrame.setVisible(true);
    }//GEN-LAST:event_rotacionDeInventarioMouseClicked

    private void resolverRotacionInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resolverRotacionInventarioMouseClicked
        // TODO add your handling code here:
        FormulasAnalisisFinanciero faf =  new FormulasAnalisisFinanciero();
        Double cosVentas, inven;
        String actCirculante = txtCosVen.getText();
        String pasCirculante = txtInvn.getText();
        cosVentas = Double.parseDouble(actCirculante);
        inven = Double.parseDouble(pasCirculante);
        Double resul = faf.calcularRotacionDeInventario(cosVentas, inven);
        String res = String.valueOf(resul);
        resultadoRotacionInventario.setText(res);
    }//GEN-LAST:event_resolverRotacionInventarioMouseClicked

    private void resPromedioCobroDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resPromedioCobroDiaMouseClicked
        // TODO add your handling code here:
        FormulasAnalisisFinanciero faf =  new FormulasAnalisisFinanciero();
        Double actcir, venxdia;
        String actcirr = txtCuentasxCobrar.getText();
        String venxdiaa = txtVentxDia.getText();
        actcir = Double.parseDouble(actcirr);
        venxdia = Double.parseDouble(venxdiaa);
        Double resul = faf.calcularPeriodoPromedioDeCobroUnoDia(actcir, venxdia);
        String res = String.valueOf(resul);
        resultadoPromedioCobroDia.setText(res);

    }//GEN-LAST:event_resPromedioCobroDiaMouseClicked

    private void cobroPorDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cobroPorDiaMouseClicked
        // TODO add your handling code here:
            promedioDeCobroDiaFrame.setBounds(0, 0, 500, 300);
            promedioDeCobroDiaFrame.setLocationRelativeTo(null); // Centra la ventana.
            promedioDeCobroDiaFrame.setVisible(true);
    }//GEN-LAST:event_cobroPorDiaMouseClicked

    private void resPromedioCobroAnualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resPromedioCobroAnualMouseClicked
        // TODO add your handling code here:
        FormulasAnalisisFinanciero faf =  new FormulasAnalisisFinanciero();
        Double actcir, venxdia;
        String actcirr = txtCuentasxCobrar1.getText();
        String venxdiaa = txtVentxAnual.getText();
        actcir = Double.parseDouble(actcirr);
        venxdia = Double.parseDouble(venxdiaa);
        Double resul = faf.calcularPeriodoPromedioDeCobroDosAnual(actcir, venxdia);
        String res = String.valueOf(resul);
        resultadoPromedioCobroAnual.setText(res);

    }//GEN-LAST:event_resPromedioCobroAnualMouseClicked

    private void cobroAnualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cobroAnualMouseClicked
        // TODO add your handling code here:
            promedioDeCobroAnualFrame.setBounds(0, 0, 500, 300);
            promedioDeCobroAnualFrame.setLocationRelativeTo(null); // Centra la ventana.
            promedioDeCobroAnualFrame.setVisible(true);
    }//GEN-LAST:event_cobroAnualMouseClicked

    private void pagoPorDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagoPorDiaMouseClicked
        // TODO add your handling code here:
            promedioDePagoPorDiaFrame.setBounds(0, 0, 500, 300);
            promedioDePagoPorDiaFrame.setLocationRelativeTo(null); // Centra la ventana.
            promedioDePagoPorDiaFrame.setVisible(true);
    }//GEN-LAST:event_pagoPorDiaMouseClicked

    private void pagoAnualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagoAnualMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pagoAnualMouseClicked

    private void rotacionDeActivosTotalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotacionDeActivosTotalesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rotacionDeActivosTotalesMouseClicked

    private void utilidadBrutaVCVVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilidadBrutaVCVVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_utilidadBrutaVCVVMouseClicked

    private void utilidadBrutaUNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilidadBrutaUNVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_utilidadBrutaUNVMouseClicked

    private void utilidadOperativaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilidadOperativaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_utilidadOperativaMouseClicked

    private void utilidadNetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilidadNetaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_utilidadNetaMouseClicked

    private void utilidadSobreActivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilidadSobreActivosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_utilidadSobreActivosMouseClicked

    private void utilidadSobreCapitalContableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilidadSobreCapitalContableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_utilidadSobreCapitalContableMouseClicked

    private void razonDeDeudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_razonDeDeudaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_razonDeDeudaMouseClicked

    private void capacidadDePagoDeInteresesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capacidadDePagoDeInteresesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadDePagoDeInteresesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel Instruciones;
    javax.swing.JLabel Titulo;
    javax.swing.JTextField activoCirculante;
    javax.swing.JTextField activoCirculante1;
    javax.swing.JButton capacidadDePagoDeIntereses;
    javax.swing.JButton capitalDeTrabajoNeto;
    javax.swing.JFrame capitalTrabajoFrame;
    javax.swing.JButton cobroAnual;
    javax.swing.JButton cobroPorDia;
    javax.swing.JLabel instru;
    javax.swing.JLabel instrudeInventario;
    javax.swing.JLabel instrudeInventario1;
    javax.swing.JLabel instrudeInventario2;
    javax.swing.JLabel instrudeInventario3;
    javax.swing.JProgressBar jProgressBar1;
    javax.swing.JPanel mainPanel;
    javax.swing.JMenuBar menuBar;
    javax.swing.JButton pagoAnual;
    javax.swing.JButton pagoPorDia;
    javax.swing.JTextField pasivoCirculante;
    javax.swing.JTextField pasivoCirculante1;
    javax.swing.JProgressBar progressBar;
    javax.swing.JFrame promedioDeCobroAnualFrame;
    javax.swing.JFrame promedioDeCobroDiaFrame;
    javax.swing.JFrame promedioDePagoPorDiaFrame;
    javax.swing.JFrame razonCircualanteFrame;
    javax.swing.JToggleButton razonCirculante;
    javax.swing.JButton razonDeDeuda;
    javax.swing.JButton razonRapida;
    javax.swing.JFrame razonRapidaFrame;
    javax.swing.JButton resPromedioCobroAnual;
    javax.swing.JButton resPromedioCobroDia;
    javax.swing.JButton resPromedioPagoPorDia;
    javax.swing.JLabel resRazonRapida;
    javax.swing.JToggleButton resolver1;
    javax.swing.JToggleButton resolverRazonCirculante;
    javax.swing.JButton resolverRazonRapida;
    javax.swing.JButton resolverRotacionInventario;
    javax.swing.JLabel resultado;
    javax.swing.JLabel resultadoPromedioCobroAnual;
    javax.swing.JLabel resultadoPromedioCobroAnual1;
    javax.swing.JLabel resultadoPromedioCobroDia;
    javax.swing.JLabel resultadoRazonCirculante;
    javax.swing.JLabel resultadoRotacionInventario;
    javax.swing.JButton rotacionDeActivosTotales;
    javax.swing.JButton rotacionDeInventario;
    javax.swing.JFrame rotacionDeInventarioFrame;
    javax.swing.JLabel statusAnimationLabel;
    javax.swing.JLabel statusMessageLabel;
    javax.swing.JPanel statusPanel;
    javax.swing.JSeparator statusPanelSeparator;
    javax.swing.JLabel tituAct;
    javax.swing.JLabel tituActivoCirculante;
    javax.swing.JLabel tituActivoCirculante1;
    javax.swing.JLabel tituCalcuActividad;
    javax.swing.JLabel tituCalcuDeuda;
    javax.swing.JLabel tituCalcuLiquidez;
    javax.swing.JLabel tituCalcuRentabilidad;
    javax.swing.JLabel tituCostoVentas;
    javax.swing.JLabel tituCuentas;
    javax.swing.JLabel tituCuentas1;
    javax.swing.JLabel tituCuentas2;
    javax.swing.JLabel tituDeActividad;
    javax.swing.JLabel tituDeDeuda;
    javax.swing.JLabel tituDeLiquidez;
    javax.swing.JLabel tituDeRentabilidad;
    javax.swing.JLabel tituInv;
    javax.swing.JLabel tituInven;
    javax.swing.JLabel tituPasCir;
    javax.swing.JLabel tituPasivoCirculante;
    javax.swing.JLabel tituPasivoCirculante1;
    javax.swing.JLabel tituRes;
    javax.swing.JLabel tituResul;
    javax.swing.JLabel tituResul1;
    javax.swing.JLabel tituVentasxDia;
    javax.swing.JLabel tituVentasxDia1;
    javax.swing.JLabel tituVentasxDia2;
    javax.swing.JLabel tituloInstr;
    javax.swing.JLabel tituloInstr1;
    javax.swing.JLabel tituresu;
    javax.swing.JLabel tituresu1;
    javax.swing.JLabel tituresu2;
    javax.swing.JLabel tituresu3;
    javax.swing.JTextField txtActi;
    javax.swing.JTextField txtCosVen;
    javax.swing.JTextField txtCuentasxCobrar;
    javax.swing.JTextField txtCuentasxCobrar1;
    javax.swing.JTextField txtCuentasxCobrar2;
    javax.swing.JTextField txtInv;
    javax.swing.JTextField txtInvn;
    javax.swing.JTextField txtPasCir;
    javax.swing.JTextField txtVentxAnual;
    javax.swing.JTextField txtVentxAnual1;
    javax.swing.JTextField txtVentxDia;
    javax.swing.JButton utilidadBrutaUNV;
    javax.swing.JButton utilidadBrutaVCVV;
    javax.swing.JButton utilidadNeta;
    javax.swing.JButton utilidadOperativa;
    javax.swing.JButton utilidadSobreActivos;
    javax.swing.JButton utilidadSobreCapitalContable;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
